version: "3.9"

services:
  postgres:
      container_name: postgres
      image: postgres:16.2-alpine
      restart: unless-stopped
      
      env_file:
        .env
        
      volumes:
        - pg-data:/var/lib/postgresql/data
      
      ports:
        - "5432:5432"
      
      healthcheck:
        test: ["CMD-SHELL","pg-isready -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
        
      deploy:
        resources:
          limits:
            memory: 512M
            
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
          
volumes:
  pg-data:
    driver: local
    