name: Deploy Postgres Database

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target Environment"
        required: true
        type: choice
        options:
          - production
          - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            
      - name: Set environment
        run: |
            ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            
            sudo mkdir -p /opt/services/postgres
            sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_HOST }} /opt/services
            cd /opt/services/postgres
            
            cat > .env <<EOL
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            EOL
            
            EOF
            
      - name: Copy docker compose
        run: |
            scp docker-compose.yml \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/opt/services/postgres/
            
      - name: Restart Service
        run: |
            ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /opt/services/postgres
            docker compose pull
            docker compose down
            docker compose up -d
            EOF
    
  
     